### ISSUE TITLE
Layer after Thumbnail fail do not return info

### ISSUE THREAD

**Issue by index-git** [LayerManager/layman#435] opened 2021-08-11 09:20 UTC
After timeout error thumbnail generation, get_workspace_layer returns 'PENDING' for all asynchronous items. After patch of the layer, everything is fine. Thumbnail error: https://hub.lesprojekt.cz/flower/task/5df5025c-e30a-48e4-8a0b-dba5f5241bea

**Comment by jirik** [comment] 2021-09-14 08:58
Duplicate of #459 (same reason)

**Closed by jirik** 2021-09-14 08:58 UTC
Labels: bug, duplicate
